### ISSUE TITLE
User Model Tests

### ISSUE THREAD

**Issue by nwarwick** [nwarwick/hbd#12]
Add test coverage for the user model, ensuring all validations are working as intended

**Comment by GerryLarios** [comment]
Hello, can you assign me this issue? I want to help 👍

**Comment by nwarwick** [comment]
All yours @GerryLarios

**Comment by GerryLarios** [comment]
Thanks, I going to finish this issue before Friday 2020-10-09 @nwarwick

**Comment by GerryLarios** [comment]
@nwarwick Sorry for not finishing this issue. I'm still working on it. I don't have any blocker, I just had a lot of work in the office.

**Comment by nwarwick** [comment]
@GerryLarios Not a problem, no rush

**Comment by Jyunri** [comment]
I will take this one @nwarwick  :)
